### ISSUE TITLE
[Bug Report] Chipendium Crash

### ISSUE THREAD

**Issue by eilene-ftf** [SitekickRemastered/Game#55]
**Describe the bug**
Using the arrows in the chipendium modal (when you press and hold a chip to view it) and you have unlocked 0 chips causes the game to hang.

**To Reproduce**
1. Create a fresh account
2. Open Collection Lists
3. Choose any list
4. Press and hold on any chip to pop the modal
5. Press one of the arrows in the bottom left/right

**Expected behavior**
Game's gonna hang

**Screenshots**
![button to press](https://github.com/user-attachments/assets/4d13da95-16bd-4813-aafc-4f0f230f19f0)

**Smartphone**
 - Device: Google Pixel 6
 - OS: Android
 - Version 0.7.4

**Comment by Mattster092** [comment]
Fixed
